services:
  # Certbot - ТОЛЬКО обновление существующих сертификатов
  certbot:
    image: certbot/certbot:latest
    container_name: certbot-renewal
    entrypoint: []
    command:
      - /bin/sh
      - -c
      - |
        sleep 30
        echo "Certbot renewal service started at $(date)"
        while :; do
          echo "Checking for certificate renewal at $(date)"
          certbot renew --quiet --webroot -w /var/www/certbot
          echo "Sleeping for 12 hours..."
          sleep 43200
        done
    env_file:
      - .env
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./ssl:/ssl
      - ./webroot:/var/www/certbot
    restart: always
    networks:
      - extension_network
    healthcheck:
      test:
        - NONE
    labels:
      - com.centurion.certbot=true
      - com.centurion.ignore-updates=true

  # 2. Основной прокси сервер
  proxy_logic:
    #image: moiz303/proxy-core:${CORE_VERSION}
    build:
      context: .
      dockerfile: /proxy_logic/Dockerfile
    ports:
      - "5050:5050"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - extension_network

  # 3. Flask API
  flask_bridge:
    #image: moiz303/proxy-flask:${FLASK_VERSION}
    build:
      context: .
      dockerfile: /flask_bridge/Dockerfile
    env_file:
      - .env
    environment:
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - proxy_logic_URL=http://proxy_logic:5050
      - FLASK_ENV=production
    depends_on:
      - proxy_logic
    restart: unless-stopped
    networks:
      - extension_network

  # 5. Основной nginx с SSL (запускается после certbot)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"    # HTTP редирект
      - "443:443"  # HTTPS
      - "5000:5000" # API
    volumes:
      - ./nginx_temp.conf:/etc/nginx/nginx.conf  # Основной конфиг с SSL
      - ./ssl:/etc/ssl/certs
      - ./webroot:/var/www/certbot
    depends_on:
      - proxy_logic
      - flask_bridge
    restart: unless-stopped
    networks:
      - extension_network

networks:
  extension_network:
    driver: bridge

volumes:
  postgres_data: