events {
    worker_connections 1024;
}

http {
    # ТОЛЬКО HTTP сервер для ACME challenges
    server {
        listen 80;


        # Обязательно для certbot
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            try_files $uri =404;
        }

        location / {
            return 404;
        }
    }
}